use std::convert::From;
use std::fmt;

use actix_web::http::StatusCode;

use super::errors::{Error, Result};

pub enum Gua64 {
    QianWeiTian,
    KunWeiDi,
    ShuiLeiTun,
    ShanShuiMeng,
    ShuiTianXu,
    TianShuiSong,
    DiShuiShi,
    ShuiDiBi,
    FengTianXiaoXu,
    TianZeLv,
    DiTianTai,
    TianDiPi,
    TianHuoTongRen,
    HuoTianDaYou,
    DiShanQian,
    LeiDiYu,
    ZeLeiSui,
    ShanFengGu,
    DiZeLin,
    FengDiGuan,
    HuoLeiShiHe,
    ShanHuoBi,
    ShanDiBo,
    DiTianFu,
    TianLeiWuWang,
    ShanTianDaXu,
    ShanLeiYi,
    ZeFengDaGuo,
    KanWeiShui,
    LiWeiHuo,
    ZeShanXian,
    LeiFengHeng,
    TianShanDun,
    LeiTianDaZhuang,
    HuoDiJin,
    DiHuoMingYi,
    FengHuoJiaRen,
    HuoZeKui,
    ShuiSHanJian,
    LeiShuiXie,
    ShanZeSun,
    FengLeiYi,
    ZeTianGuai,
    TianFengGou,
    ZeDiCui,
    DiFengSheng,
    ZeShuiKun,
    ShuiFengJing,
    ZeHuoGe,
    HuoFengDing,
    ZhenWeiLei,
    GenWeiShan,
    FengShanJian,
    LeiZeGuiMei,
    LeiHuoFeng,
    HuoShanLv,
    XunWeiFeng,
    DuiWeiZe,
    FengShuiHuan,
    ShuiZeJie,
    FengZeZhongFu,
    LeiShanXiaoGuo,
    ShuoHuoJiJi,
    ShuoShuiWeiJi,
}

impl fmt::Debug for Gua64 {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::QianWeiTian => "乾為天",
                Self::KunWeiDi => "坤為地",
                Self::ShuiLeiTun => "水雷屯",
                Self::ShanShuiMeng => "山水蒙",
                Self::ShuiTianXu => "水天需",
                Self::TianShuiSong => "天水訟",
                Self::DiShuiShi => "地水師",
                Self::ShuiDiBi => "水地比",
                Self::FengTianXiaoXu => "風天小畜",
                Self::TianZeLv => "天澤履",
                Self::DiTianTai => "地天泰",
                Self::TianDiPi => "天地否",
                Self::TianHuoTongRen => "天火同人",
                Self::HuoTianDaYou => "火天大有",
                Self::DiShanQian => "地山謙",
                Self::LeiDiYu => "雷地豫",
                Self::ZeLeiSui => "澤雷隨",
                Self::ShanFengGu => "山風蠱",
                Self::DiZeLin => "地澤臨",
                Self::FengDiGuan => "風地觀",
                Self::HuoLeiShiHe => "火雷噬嗑",
                Self::ShanHuoBi => "山火賁",
                Self::ShanDiBo => "山地剝",
                Self::DiTianFu => "地雷復",
                Self::TianLeiWuWang => "天雷無妄",
                Self::ShanTianDaXu => "山天大畜",
                Self::ShanLeiYi => "山雷頤",
                Self::ZeFengDaGuo => "澤風大過",
                Self::KanWeiShui => "坎為水",
                Self::LiWeiHuo => "離為火",
                Self::ZeShanXian => "澤山咸",
                Self::LeiFengHeng => "雷風恆",
                Self::TianShanDun => "天山遯",
                Self::LeiTianDaZhuang => "雷天大壯",
                Self::HuoDiJin => "火地晉",
                Self::DiHuoMingYi => "地火明夷",
                Self::FengHuoJiaRen => "風火家人",
                Self::HuoZeKui => "火澤睽",
                Self::ShuiSHanJian => "水山蹇",
                Self::LeiShuiXie => "雷水解",
                Self::ShanZeSun => "山澤損",
                Self::FengLeiYi => "風雷益",
                Self::ZeTianGuai => "澤天夬",
                Self::TianFengGou => "天風姤",
                Self::ZeDiCui => "澤地萃",
                Self::DiFengSheng => "地風升",
                Self::ZeShuiKun => "澤水困",
                Self::ShuiFengJing => "水風井",
                Self::ZeHuoGe => "澤火革",
                Self::HuoFengDing => "火風鼎",
                Self::ZhenWeiLei => "震為雷",
                Self::GenWeiShan => "艮為山",
                Self::FengShanJian => "風山漸",
                Self::LeiZeGuiMei => "雷澤歸妹",
                Self::LeiHuoFeng => "雷火豐",
                Self::HuoShanLv => "火山旅",
                Self::XunWeiFeng => "巽為風",
                Self::DuiWeiZe => "兌為澤",
                Self::FengShuiHuan => "風水渙",
                Self::ShuiZeJie => "水澤節",
                Self::FengZeZhongFu => "風澤中孚",
                Self::LeiShanXiaoGuo => "雷山小過",
                Self::ShuoHuoJiJi => "水火既濟",
                Self::ShuoShuiWeiJi => "火水未濟",
            }
        )
    }
}

impl fmt::Display for Gua64 {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::QianWeiTian => "\u{4DC0}",
                Self::KunWeiDi => "\u{4DC1}",
                Self::ShuiLeiTun => "\u{4DC2}",
                Self::ShanShuiMeng => "\u{4DC3}",
                Self::ShuiTianXu => "\u{4DC4}",
                Self::TianShuiSong => "\u{4DC5}",
                Self::DiShuiShi => "\u{4DC6}",
                Self::ShuiDiBi => "\u{4DC7}",
                Self::FengTianXiaoXu => "\u{4DC8}",
                Self::TianZeLv => "\u{4DC9}",
                Self::DiTianTai => "\u{4DCA}",
                Self::TianDiPi => "\u{4DCB}",
                Self::TianHuoTongRen => "\u{4DCC}",
                Self::HuoTianDaYou => "\u{4DCD}",
                Self::DiShanQian => "\u{4DCE}",
                Self::LeiDiYu => "\u{4DCF}",
                Self::ZeLeiSui => "\u{4DD0}",
                Self::ShanFengGu => "\u{4DD1}",
                Self::DiZeLin => "\u{4DD2}",
                Self::FengDiGuan => "\u{4DD3}",
                Self::HuoLeiShiHe => "\u{4DD4}",
                Self::ShanHuoBi => "\u{4DD5}",
                Self::ShanDiBo => "\u{4DD6}",
                Self::DiTianFu => "\u{4DD7}",
                Self::TianLeiWuWang => "\u{4DD8}",
                Self::ShanTianDaXu => "\u{4DD9}",
                Self::ShanLeiYi => "\u{4DDA}",
                Self::ZeFengDaGuo => "\u{4DDB}",
                Self::KanWeiShui => "\u{4DDC}",
                Self::LiWeiHuo => "\u{4DDD}",
                Self::ZeShanXian => "\u{4DDE}",
                Self::LeiFengHeng => "\u{4DDF}",
                Self::TianShanDun => "\u{4DE0}",
                Self::LeiTianDaZhuang => "\u{4DE1}",
                Self::HuoDiJin => "\u{4DE2}",
                Self::DiHuoMingYi => "\u{4DE3}",
                Self::FengHuoJiaRen => "\u{4DE4}",
                Self::HuoZeKui => "\u{4DE5}",
                Self::ShuiSHanJian => "\u{4DE6}",
                Self::LeiShuiXie => "\u{4DE7}",
                Self::ShanZeSun => "\u{4DE8}",
                Self::FengLeiYi => "\u{4DE9}",
                Self::ZeTianGuai => "\u{4DEA}",
                Self::TianFengGou => "\u{4DEB}",
                Self::ZeDiCui => "\u{4DEC}",
                Self::DiFengSheng => "\u{4DED}",
                Self::ZeShuiKun => "\u{4DEE}",
                Self::ShuiFengJing => "\u{4DEF}",
                Self::ZeHuoGe => "\u{4DF0}",
                Self::HuoFengDing => "\u{4DF1}",
                Self::ZhenWeiLei => "\u{4DF2}",
                Self::GenWeiShan => "\u{4DF3}",
                Self::FengShanJian => "\u{4DF4}",
                Self::LeiZeGuiMei => "\u{4DF5}",
                Self::LeiHuoFeng => "\u{4DF6}",
                Self::HuoShanLv => "\u{4DF7}",
                Self::XunWeiFeng => "\u{4DF8}",
                Self::DuiWeiZe => "\u{4DF9}",
                Self::FengShuiHuan => "\u{4DFA}",
                Self::ShuiZeJie => "\u{4DFB}",
                Self::FengZeZhongFu => "\u{4DFC}",
                Self::LeiShanXiaoGuo => "\u{4DFD}",
                Self::ShuoHuoJiJi => "\u{4DFE}",
                Self::ShuoShuiWeiJi => "\u{4DFF}",
            }
        )
    }
}

impl Gua64 {
    pub fn new(v: u16) -> Result<Self> {
        match v {
            0x4DC0 => Ok(Self::QianWeiTian),
            0x4DC1 => Ok(Self::KunWeiDi),
            0x4DC2 => Ok(Self::ShuiLeiTun),
            0x4DC3 => Ok(Self::ShanShuiMeng),
            0x4DC4 => Ok(Self::ShuiTianXu),
            0x4DC5 => Ok(Self::TianShuiSong),
            0x4DC6 => Ok(Self::DiShuiShi),
            0x4DC7 => Ok(Self::ShuiDiBi),
            0x4DC8 => Ok(Self::FengTianXiaoXu),
            0x4DC9 => Ok(Self::TianZeLv),
            0x4DCA => Ok(Self::DiTianTai),
            0x4DCB => Ok(Self::TianDiPi),
            0x4DCC => Ok(Self::TianHuoTongRen),
            0x4DCD => Ok(Self::HuoTianDaYou),
            0x4DCE => Ok(Self::DiShanQian),
            0x4DCF => Ok(Self::LeiDiYu),
            0x4DD0 => Ok(Self::ZeLeiSui),
            0x4DD1 => Ok(Self::ShanFengGu),
            0x4DD2 => Ok(Self::DiZeLin),
            0x4DD3 => Ok(Self::FengDiGuan),
            0x4DD4 => Ok(Self::HuoLeiShiHe),
            0x4DD5 => Ok(Self::ShanHuoBi),
            0x4DD6 => Ok(Self::ShanDiBo),
            0x4DD7 => Ok(Self::DiTianFu),
            0x4DD8 => Ok(Self::TianLeiWuWang),
            0x4DD9 => Ok(Self::ShanTianDaXu),
            0x4DDA => Ok(Self::ShanLeiYi),
            0x4DDB => Ok(Self::ZeFengDaGuo),
            0x4DDC => Ok(Self::KanWeiShui),
            0x4DDD => Ok(Self::LiWeiHuo),
            0x4DDE => Ok(Self::ZeShanXian),
            0x4DDF => Ok(Self::LeiFengHeng),
            0x4DE0 => Ok(Self::TianShanDun),
            0x4DE1 => Ok(Self::LeiTianDaZhuang),
            0x4DE2 => Ok(Self::HuoDiJin),
            0x4DE3 => Ok(Self::DiHuoMingYi),
            0x4DE4 => Ok(Self::FengHuoJiaRen),
            0x4DE5 => Ok(Self::HuoZeKui),
            0x4DE6 => Ok(Self::ShuiSHanJian),
            0x4DE7 => Ok(Self::LeiShuiXie),
            0x4DE8 => Ok(Self::ShanZeSun),
            0x4DE9 => Ok(Self::FengLeiYi),
            0x4DEA => Ok(Self::ZeTianGuai),
            0x4DEB => Ok(Self::TianFengGou),
            0x4DEC => Ok(Self::ZeDiCui),
            0x4DED => Ok(Self::DiFengSheng),
            0x4DEE => Ok(Self::ZeShuiKun),
            0x4DEF => Ok(Self::ShuiFengJing),
            0x4DF0 => Ok(Self::ZeHuoGe),
            0x4DF1 => Ok(Self::HuoFengDing),
            0x4DF2 => Ok(Self::ZhenWeiLei),
            0x4DF3 => Ok(Self::GenWeiShan),
            0x4DF4 => Ok(Self::FengShanJian),
            0x4DF5 => Ok(Self::LeiZeGuiMei),
            0x4DF6 => Ok(Self::LeiHuoFeng),
            0x4DF7 => Ok(Self::HuoShanLv),
            0x4DF8 => Ok(Self::XunWeiFeng),
            0x4DF9 => Ok(Self::DuiWeiZe),
            0x4DFA => Ok(Self::FengShuiHuan),
            0x4DFB => Ok(Self::ShuiZeJie),
            0x4DFC => Ok(Self::FengZeZhongFu),
            0x4DFD => Ok(Self::LeiShanXiaoGuo),
            0x4DFE => Ok(Self::ShuoHuoJiJi),
            0x4DFF => Ok(Self::ShuoShuiWeiJi),
            _ => Err(Error::Http(
                StatusCode::BAD_REQUEST,
                Some(format!("bad Gua64 number {}", v)),
            )),
        }
    }
}

impl From<Gua64> for u16 {
    fn from(item: Gua64) -> Self {
        match item {
            Gua64::QianWeiTian => 0x4DC0,
            Gua64::KunWeiDi => 0x4DC1,
            Gua64::ShuiLeiTun => 0x4D,
            Gua64::ShanShuiMeng => 0x4D,
            Gua64::ShuiTianXu => 0x4D,
            Gua64::TianShuiSong => 0x4D,
            Gua64::DiShuiShi => 0x4D,
            Gua64::ShuiDiBi => 0x4D,
            Gua64::FengTianXiaoXu => 0x4D,
            Gua64::TianZeLv => 0x4D,
            Gua64::DiTianTai => 0x4D,
            Gua64::TianDiPi => 0x4D,
            Gua64::TianHuoTongRen => 0x4D,
            Gua64::HuoTianDaYou => 0x4D,
            Gua64::DiShanQian => 0x4D,
            Gua64::LeiDiYu => 0x4D,
            Gua64::ZeLeiSui => 0x4D,
            Gua64::ShanFengGu => 0x4D,
            Gua64::DiZeLin => 0x4D,
            Gua64::FengDiGuan => 0x4D,
            Gua64::HuoLeiShiHe => 0x4D,
            Gua64::ShanHuoBi => 0x4D,
            Gua64::ShanDiBo => 0x4D,
            Gua64::DiTianFu => 0x4D,
            Gua64::TianLeiWuWang => 0x4D,
            Gua64::ShanTianDaXu => 0x4D,
            Gua64::ShanLeiYi => 0x4D,
            Gua64::ZeFengDaGuo => 0x4D,
            Gua64::KanWeiShui => 0x4D,
            Gua64::LiWeiHuo => 0x4D,
            Gua64::ZeShanXian => 0x4D,
            Gua64::LeiFengHeng => 0x4D,
            Gua64::TianShanDun => 0x4D,
            Gua64::LeiTianDaZhuang => 0x4D,
            Gua64::HuoDiJin => 0x4D,
            Gua64::DiHuoMingYi => 0x4D,
            Gua64::FengHuoJiaRen => 0x4D,
            Gua64::HuoZeKui => 0x4D,
            Gua64::ShuiSHanJian => 0x4D,
            Gua64::LeiShuiXie => 0x4D,
            Gua64::ShanZeSun => 0x4D,
            Gua64::FengLeiYi => 0x4D,
            Gua64::ZeTianGuai => 0x4D,
            Gua64::TianFengGou => 0x4D,
            Gua64::ZeDiCui => 0x4D,
            Gua64::DiFengSheng => 0x4D,
            Gua64::ZeShuiKun => 0x4D,
            Gua64::ShuiFengJing => 0x4D,
            Gua64::ZeHuoGe => 0x4D,
            Gua64::HuoFengDing => 0x4D,
            Gua64::ZhenWeiLei => 0x4D,
            Gua64::GenWeiShan => 0x4D,
            Gua64::FengShanJian => 0x4D,
            Gua64::LeiZeGuiMei => 0x4D,
            Gua64::LeiHuoFeng => 0x4D,
            Gua64::HuoShanLv => 0x4D,
            Gua64::XunWeiFeng => 0x4D,
            Gua64::DuiWeiZe => 0x4D,
            Gua64::FengShuiHuan => 0x4D,
            Gua64::ShuiZeJie => 0x4D,
            Gua64::FengZeZhongFu => 0x4D,
            Gua64::LeiShanXiaoGuo => 0x4D,
            Gua64::ShuoHuoJiJi => 0x4D,
            Gua64::ShuoShuiWeiJi => 0x4D,
        }
    }
}
